// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-yuvq0nlcviykZfDQV5Ns5nt3cmNo4c',
    appId: '1:296861109418:web:5c97e7b42e9e15741e94d3',
    messagingSenderId: '296861109418',
    projectId: 'food-delivery-469a7',
    authDomain: 'food-delivery-469a7.firebaseapp.com',
    storageBucket: 'food-delivery-469a7.appspot.com',
    measurementId: 'G-RTH591FZ6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_wpNWKszmYkmBORuzOQJyMybW7_CDFRE',
    appId: '1:296861109418:android:91d968a11fe2f8331e94d3',
    messagingSenderId: '296861109418',
    projectId: 'food-delivery-469a7',
    storageBucket: 'food-delivery-469a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjIOkC7eP6iTJ_Emko94T8tHj7oCokX5o',
    appId: '1:296861109418:ios:2a70ee09b7f846261e94d3',
    messagingSenderId: '296861109418',
    projectId: 'food-delivery-469a7',
    storageBucket: 'food-delivery-469a7.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjIOkC7eP6iTJ_Emko94T8tHj7oCokX5o',
    appId: '1:296861109418:ios:2a70ee09b7f846261e94d3',
    messagingSenderId: '296861109418',
    projectId: 'food-delivery-469a7',
    storageBucket: 'food-delivery-469a7.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-yuvq0nlcviykZfDQV5Ns5nt3cmNo4c',
    appId: '1:296861109418:web:f3cbfa0eee4fa8851e94d3',
    messagingSenderId: '296861109418',
    projectId: 'food-delivery-469a7',
    authDomain: 'food-delivery-469a7.firebaseapp.com',
    storageBucket: 'food-delivery-469a7.appspot.com',
    measurementId: 'G-ZSP9066YQ7',
  );
}
